apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: movieswipe

resources:
  - ../base

images:
  - name: ghcr.io/brk3/movieswipe
    newName: forgejo.aiectomy.xyz/pbourke/movieswipe
    newTag: latest

secretGenerator:
  - name: movieswipe-api-keys
    envs:
      - .env
    options:
      disableNameSuffixHash: true
